alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias poweroff='sudo systemctl poweroff -i'
alias vim='nvim'
alias tree='tree -aC -I .git'
alias push-music='adbsync ~/Music/Main/ /sdcard/Music/Vault'

PS1="\[\e[1;31m\]\w\[\e[0m\] \$ "

source /etc/profile.d/vte.sh
source $HOME/.local/share/bash/command-not-found.bash

set -o vi
