ytdl-format="bestvideo[vcodec!=vp9][vcodec!=opus][height<=?720]+bestaudio/best"
cache
demuxer-max-bytes=2048M
demuxer-readahead-secs=1800
osd-font="monospace"
osd-font-size=55
no-audio-pitch-correction
speed=1.00
directory-mode=recursive
autocreate-playlist=filter
directory-filter-types=video,audio
loop-playlist=inf
force-window=immediate
